---
- name: "Install utils"
  hosts: "all"
  become: true

  tasks:
    - name: Set timezone Moscow
      community.general.timezone:
        name: Europe/Moscow

    - name: "Add epel-release repo"
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: "Install nfs-utils"
      ansible.builtin.yum:
       name: "nfs-utils"
       state: present

    - name: "Install borgbackup"
      ansible.builtin.yum:
        name: borgbackup
        state: present

    - name: "Add user borg"
      user: 
        name: borg
        shell: /bin/bash
        append: yes

- name: "Settings backup-client"
  hosts: "clients"
  become: true

  tasks:
    - name: "Create directory .ssh"
      ansible.builtin.file:
        path: /home/borg/.ssh/
        mode: '0700'
        state: directory

    - name: "Ssh-keygen"
      ansible.builtin.user:
        name: borg
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa

    # - name: "Ssh-keygen"
    #   shell: "cd /home/borg/.ssh/ \ ssh-keygen"

    - name: "Copy ssh-key on server"
      fetch:
        src: /root/.ssh/id_rsa.pub
        dest: ./key/id_rsa.pub
        flat: true

    # - name: "Mount remote directory /var/backup"
    #   shell: "borg init --encryption=repokey borg@192.168.11.160:/var/backup/"
    
    # - name: "Mount remote directory /var/backup"
    #   ansible.posix.mount:
    #     src: 192.168.11.160:/var/backup
    #     path: /mnt/backup
    #     opts: rw,sync,hard
    #     state: mounted
    #     fstype: nfs

    # # - name: "Install borg"
    # #   shell: 


- name: "Settings backup-server"
  hosts: "backup_server"
  become: true

  tasks:
    - name: "Create filesystem ext4"
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: "Mount up device by label"
      ansible.posix.mount:
        path: /var/backup
        src: /dev/sdb
        fstype: ext4
        state: mounted

    # - name: "Add user borg"
    #   user: 
    #     name: borg
    #     shell: /bin/bash
    #     append: yes

    - name: "Creates directory /var/backup"
      ansible.builtin.file:
        path: /var/backup
        owner: borg
        group: borg
        mode: '0644'
        state: directory

    - name: "Create directory .ssh"
      ansible.builtin.file:
        path: /home/borg/.ssh/
        mode: '0700'
        state: directory
    
    - name: "Create file-key .ssh"
      ansible.builtin.file:
        path: /home/borg/.ssh/authorized_keys
        owner: borg
        group: borg
        mode: '0600'
        state: touch

    # - name: "Create directory .ssh"
    #   ansible.builtin.user:
    #     name: borg
    #     generate_ssh_key: yes
    #     ssh_key_bits: 2048
    #     ssh_key_file: /home/borg/.ssh/id_rsa
    
    # - name: "Copy ssh-key"
    #   fetch:
    #     src: /home/borg/.ssh/id_rsa.pub
    #     dest: ./key/id_rsa.pub
    #     flat: true
    - name: "Copy ssh-key"
      copy:
        src: ./key/id_rsa.pub
        dest: /home/borg/.ssh/me.pub

    - name: "Add ssh-key into authorized_keys"
      shell: "cat /home/borg/.ssh/me.pub >> /home/borg/.ssh/authorized_keys"
      